#
#   JPEG 2000 decoder.
#
#   Decoding, which uses OpenJPEG in C, runs in a subprocess, for safety.
#
#   Usable targets:
#   - native (on Linux)
#   - x86_64-pc-windows-gnu
#   - (MacOS pending)
#
[package]
name = "jpeg2000-decoder"
version = "0.1.2"
edition = "2021"
authors = ["John Nagle <nagle@animats.com>"]
license = "LGPL"
description = "JPEG 2000 image loader."
keywords = ["j2k", "jp2", "jpeg2000", "image"]
repository = "https://github.com/John-Nagle/jpeg2000-decoder"
homepage = "https://github.com/John-Nagle/jpeg2000-decoder"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "jpeg2000_decoder"
path = "src/lib/lib.rs"

[[bin]]
name = "jpeg2000_decoder"
path = "src/bin/jpeg2000_decoder/main.rs" # replace bin.rs with name of your file

[dependencies]

#   The OpenJPEG decoder.
####jpeg2k = "0.6.2"
jpeg2k = {version = "0.6.3", default-features = false, features = ["image", "strict-mode", "openjpeg-sys"]}

#   LLSD handler
serde-llsd = "0.1.0"

#   Images
image = {version = "0.24.6", default-features = false, features = ["png"]}
####image = "0.23.14"

#   Network
ureq = "2.6.2"

#   Misc.
anyhow = "1"
argparse = "0.2.2"
url = "2.3"
parking_lot = "0.12"

#   For tests.
crossbeam-channel = "0.5"
thread-priority = "0.13"
log = "0.4"
profiling = "1.0"
simple_logger = "4.1"
